# Need to use Conda to build Shakemap, pull the Docker image
default:
  image: ${DEVOPS_REGISTRY}usgs/python:3.9
  tags:
    - development

  before_script:
    - python --version
    - export PATH="/home/usgs-user/.local/bin:$PATH"
    - mini_conda_url=https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - curl -L $mini_conda_url -o miniconda.sh
    - bash miniconda.sh -f -b -p $HOME/miniconda
    - . $HOME/miniconda/etc/profile.d/conda.sh
    - conda install -c conda-forge -y tree make

# repository rules
.fork: &fork
  if: >
    $CI_PROJECT_PATH != 'ghsc/esi/shakemap'
    && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
  variables:
    ENVIRONMENT: development

.upstream: &upstream
  if: >
    $CI_PROJECT_PATH == 'ghsc/esi/shakemap'
    && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  variables:
    ENVIRONMENT: staging

# For now, just set up a testing stagge to run PyTest
stages:
  - test
  - build
  - docs

# Create parallel pipeline and job version configuration
.versions:
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.9", "3.10"]

# Create reusable build configuration for referencing
.build_config:
  script:
    - conda init bash
    - bash install.sh -p ${PYTHON_VERSION}
    - conda activate shakemap
    - strec_cfg update --datafolder /root/.strec/data --slab --gcmt

# Create test job
run tests and coverage:
  stage: test
  script:
    # Run build configuration script
    - !reference [.build_config, script]

    # Continue job script
    - pytest -x --cov=shakemap --cov-report xml:coverage.xml --cov-report term --junitxml junit.xml
    - coverage xml

  # Define test coverage and reporting
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: junit.xml

  rules:
    - *fork
    - *upstream

  # Run the jobs as parallel pipelines
  parallel: !reference [.versions, parallel]

pages:
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only merges to the default branch will trigger
    # a pages deploy
    - <<: *upstream
      when: on_success

  script:
    # Run build configuration script
    - !reference [.build_config, script]
    - cd doc_source
    - pip install -r requirements.txt
    - cd ..
    - sphinx-build doc_source/ public
  stage: docs